### ISSUE TITLE
Sleeptimer in Darkmode not readable

### ISSUE THREAD

**Issue by CptPie** [deep-gaurav/MusicPiped#68]
### Description
When using Dark Mode the time chosen in the sleep timer menu is not readable:
Dark Mode:
![DarkMode](https://user-images.githubusercontent.com/23438606/56448181-7e86d100-630d-11e9-82c4-bf0a9381e130.png)
Light Mode:
![LightMode](https://user-images.githubusercontent.com/23438606/56448182-7e86d100-630d-11e9-96f3-a4303b10812b.png)

### Expected behaviour
Timer should be readable like in Light Mode.

### Actual behaviour
Timer is not readable in Dark Mode.

### How to reproduce
- Switch the app into Dark Mode
- Start music
- Try to set a sleep timer

### Technical Details
App Version: 1.1.3 (downloaded via FDroid)
Android Version: 8.1.0

**Comment by deep-gaurav** [comment]
Thanks for reporting, it'll be fixed in next update

**Comment by deep-gaurav** [comment]
Should be fixed in latest release V1.1.4

**Comment by CptPie** [comment]
I am sad to say the problem is still present after the update to 1.1.4 (even restarted the phone) If you need any information about my device I will provide it.

**Comment by CptPie** [comment]
@deep-gaurav - I am sad to say the problem is still present after the update to 1.1.4 (even restarted the phone) If you need any information about my device I will provide it.

**Comment by deep-gaurav** [comment]
Can you paste another screenshot from v1.1.4 this is how it should appear
![Screenshot_20190423-072231](https://user-images.githubusercontent.com/28472450/56546826-fc93e380-656a-11e9-82b1-7133e04355c0.png)

Reopening issue

**Comment by CptPie** [comment]
Screenshot in Version 1.1.4:
![DarkMode_1 1 4](https://user-images.githubusercontent.com/23438606/56555727-0c74ed00-6596-11e9-807f-d63fbbbc7af2.png)
Version based on FDroid:
![Fdroid](https://user-images.githubusercontent.com/23438606/56555742-1a2a7280-6596-11e9-9f0b-4b0c51a752bc.jpg)

**Comment by deep-gaurav** [comment]
Can you update me if it persists in v1.2.0 (just released)

**Comment by CptPie** [comment]
I just updated and the problem still persists. 
By now I think it might be a problem with my device instead of the app.
I'll reinstall my phone (was already planned anyways) and will then report back.
Until then I believe this issue can be closed
